# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      # specify the version
      - image: alpine:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
        #- checkout

      # specify any bash command here prefixed with `run: `
      - run: echo "Calling API to start tests"
      - run: wget --spider -S -q https://iscircleciup.net
      - run: date
  build:
    docker:
      # specify the version
      - image: alpine:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
        #- checkout

      # specify any bash command here prefixed with `run: `
      - run: echo "Calling API to start build"
      - run: wget --spider -S -q https://iscircleciup.net
      - run: date
  deliver:
    docker:
      # specify the version
      - image: alpine:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
        #- checkout

      # specify any bash command here prefixed with `run: `
      - run: echo "Calling API to deliver to artifact store"
      - run: wget --spider -S -q https://iscircleciup.net
      - run: date
  spinup_test_env:
    docker:
      # specify the version
      - image: alpine:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
        #- checkout

      # specify any bash command here prefixed with `run: `
      - run: echo "Calling API to spinup test environment"
      - run: wget --spider -S -q https://iscircleciup.net
      - run: date
  integration_test:
    docker:
      # specify the version
      - image: alpine:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
        #- checkout

      # specify any bash command here prefixed with `run: `
      - run: echo "Calling API to run Cypress Tests"
      - run: wget --spider -S -q https://iscircleciup.net
      - run: date
  deployment:
    docker:
      # specify the version
      - image: alpine:latest

    steps:
        #- checkout

      # specify any bash command here prefixed with `run: `
      - run: echo "Calling API to promote artifact"
      - run: wget --spider -S -q https://iscircleciup.net
      - run: date


##
##
## Workflows
##
##
workflows:
    version: 2
    Delivery:
        jobs:
            - test
            - build:
                requires:
                    - test
            - deliver:
                requires:
                    - build
            - spinup_test_env:
                requires:
                    - deliver
            - integration_test:
                requires:
                    - spinup_test_env
            - promote_artifact:
                requires:
                    - integration_test
